name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cahce: yarn

    - name: Build
      run: |
        yarn
        yarn build

    - name: Result
      run: |
        ls -al
        mv dist tabs
        
    - name: SSH Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: vecchio.top
        # Remote user
        REMOTE_USER: ${{ secrets.USERNAME }}
        # Remote port
        REMOTE_PORT: 22 # optional, default is 22
        # Source directory
        SOURCE: tabs # optional, default is
        # Target directory
        TARGET: /usr/share/nginx/ # optional, default is /home/REMOTE_USER/
        # Arguments to pass to rsync
        # ARGS: # optional, default is -rltgoDzvO
        # An array of folder to exclude
        # EXCLUDE: # optional, default is
